version: '3'
services:
  db:
    container_name: postgres
    image: postgres:9.6
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PWD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
  database:
